name: Changelog

on:
  pull_request:
    branches:
      - main

jobs:
  check-and-comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - name: Check CHANGES.rst Updated
        run: |
          git fetch origin main:main
          updated_files=$(git diff main -- CHANGES.rst)
          if [[ -z $updated_files ]]
          then
            exit 1
          fi

      - name: Comment PR
        if: ${{ failure() }}
        uses: thollander/actions-comment-pull-request@v1
        with:
          comment_includes: "changelog" # To avoid creating additional comments
          message: |
            Please include the change for this PR in the changelog (`CHANGES.rst`).
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
